// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/data/portfolio.ts
var personalInfo = {
  name: "Achyuth Mukund",
  location: "Chennai, Tamil Nadu",
  tagline: "Building Intelligent Systems",
  description: "Software developer crafting intelligent systems at the intersection of GenAI, IoT, and ML. Shipping clean code that solves real problems.",
  email: "achyuth2004@gmail.com",
  phone: "+91 73584 41472",
  social: {
    github: "https://github.com/achyuth-2308",
    linkedin: "https://www.linkedin.com/in/achyuth-mukund/",
    youtube: "https://www.youtube.com/@AchyuthMukund",
    instagram: "https://instagram.com/achyuth_2308",
    medium: "https://medium.com/@achyuth_2308",
    researchgate: "https://www.researchgate.net/profile/Achyuth-Mukund",
    orcid: "https://orcid.org/0009-0002-5798-0858",
    linktree: "https://linktr.ee/achyuth.mukund"
  }
};
var about = {
  bio: "Motivated and versatile developer with a strong sense of responsibility and discipline, committed to delivering efficient, high-performance software solutions. Eager to contribute to innovative, impact-driven projects while enhancing technical expertise and problem-solving capabilities in real-world environments.",
  education: [
    {
      degree: "B.Tech, Computer Science & Engineering",
      specialization: "Internet of Things (IoT)",
      institution: "Shiv Nadar University Chennai",
      duration: "2022 - 2026 (Completed)",
      grade: "CGPA: 7.62/10",
      coursework: [
        "Data Structures",
        "Design and Analysis of Algorithms",
        "Artificial Intelligence",
        "Operating Systems",
        "Web Technologies",
        "Computer Networks",
        "Sensor Technologies",
        "Internet of Things",
        "Machine Learning Technologies and Algorithms",
        "Cryptography",
        "Blockchain Development"
      ],
      activities: [
        {
          icon: "Coffee",
          title: "Founder \u2014 Central Perk Caf\xE9",
          description: "Kickstarted the university's first ever student-run entrepreneurial venture on campus.",
          tag: "Entrepreneurship",
          year: "2023 \u2014 Present",
          story: "Central Perk Caf\xE9 is the first ever student-run entrepreneurial venture at Shiv Nadar University Chennai. We pitched it as more than a coffee spot \u2014 a third place on campus where students, faculty, and visitors could collide over good coffee and better conversations. As a co-founder, I helped shape the brand, the menu, the operating model, and the day-one team.",
          highlights: [
            "Co-founded and launched the first student-run caf\xE9 on campus",
            "Built the brand identity, menu architecture, and pricing strategy",
            "Hired and trained the founding student-staff team",
            "Designed the in-store experience \u2014 from playlist to packaging"
          ]
        },
        {
          icon: "FlaskConical",
          title: "STIRS Researcher \u2014 Stimuli for Technological Innovation and Research by Students",
          description: "Awarded the STIRS 2023\u201324 grant for EcoSphereX \u2014 an IoT-based environmental health monitoring system.",
          tag: "Research",
          year: "2023 \u2014 2025",
          story: "STIRS (Stimuli for Technological Innovation and Research by Students) is Shiv Nadar University Chennai's flagship student-led research grant programme, run by the Office of the Vice Chancellor. Our team \u2014 Achyuth Mukund, M. Muhammad Farhaan, and B.A. Saran \u2014 was awarded the STIRS 2023\u201324 grant of \u20B910,000 under project code STIR2023_IIMSEH for EcoSphereX: an IoT-Based Integrated Monitoring System for Environmental Health, mentored by Dr. Surya K and Mr. Madankumar (Dept. of CSE, School of Engineering). The system fuses NodeMCU ESP8266, DHT-11, MQ-135 air quality, sound, soil moisture and pH sensors over MQTT to deliver real-time, location-aware readings of air, noise, water and soil health \u2014 turning a campus into a living, queryable environmental dataset. The work was later selected and presented at the All India Research Scholars' Summit (AIRSS) 2025 at IIT Madras (27\u201330 March 2025) as paper OP106.",
          highlights: [
            "STIRS 2023\u201324 Grant Awardee \u2014 \u20B910,000, Project STIR2023_IIMSEH",
            "Presented as paper OP106 at AIRSS 2025, IIT Madras",
            "Built end-to-end IoT stack: ESP8266 + DHT-11 + MQ-135 + sound/soil/pH sensors over MQTT",
            "Real-time environmental dashboard for air, noise, water and soil health",
            "Mentored by Dr. Surya K and Mr. Madankumar, Dept. of CSE, SNUC",
            "Open-sourced on GitHub: EcoSphereX repository"
          ]
        },
        {
          icon: "Users",
          title: "Vice President \u2014 SNUC MUN Society",
          description: "Led the Model United Nations society driving debate, diplomacy, and global affairs on campus.",
          tag: "Leadership",
          year: "2023 \u2014 2024",
          story: "As Vice President of the SNUC Model United Nations Society, I helped lead one of the most active intellectual communities on campus \u2014 running internal MUNs, training first-time delegates, and representing the university at external conferences.",
          highlights: [
            "Led society operations alongside the President and core team",
            "Organised and chaired multiple internal MUN conferences",
            "Trained delegates on research, rules of procedure, and diplomacy",
            "Grew active membership and external participation"
          ]
        },
        {
          icon: "Sparkles",
          title: "Overall Cultural & Club Coordinator",
          description: "Coordinated cultural events and student clubs across the university calendar.",
          tag: "Leadership",
          year: "2024 \u2014 2025",
          story: "Owned the end-to-end coordination of cultural programming and club activity across the academic year \u2014 working with every club head, the student council, and the administration to ship events on time and on brand.",
          highlights: [
            "Orchestrated the cultural calendar across all student clubs",
            "Single point of contact between clubs and the administration",
            "Drove cross-club collaboration on flagship events"
          ]
        },
        {
          icon: "Trophy",
          title: "University Cricket Team",
          description: "Part of the prestigious SNUC cricket team \u2014 right-arm medium pacer & batsman.",
          tag: "Sports",
          year: "2022 \u2014 Present",
          story: "Represented Shiv Nadar University Chennai's cricket team across inter-collegiate fixtures. Cricket has been my longest-running discipline \u2014 and the place I learned that consistency beats intensity.",
          highlights: [
            "Right-arm medium pacer and middle-order batsman",
            "Represented the university in inter-collegiate tournaments",
            "Year-round training and selection cycles"
          ]
        },
        {
          icon: "Megaphone",
          title: "Student Ambassador \u2014 SNUC",
          description: "Represented the university to prospective students, guests, and external stakeholders.",
          tag: "Outreach",
          year: "2023 \u2014 2025",
          story: "As a Student Ambassador, I was one of the faces of the university for prospective students, parents, alumni, and visiting dignitaries \u2014 running campus tours, panels, and Q&A sessions.",
          highlights: [
            "Conducted campus tours for prospective students and families",
            "Spoke on student panels during open days and admissions events",
            "Hosted visiting industry and academic guests"
          ]
        },
        {
          icon: "Palette",
          title: "Designer \u2014 Aura, SNUC Design Club",
          description: "Designed posters and creatives for various flagship events across campus.",
          tag: "Design",
          year: "2022 \u2014 2024",
          story: "As part of Aura, the official design club, I designed posters, social creatives, and event collateral for flagship cultural, technical, and academic events on campus.",
          highlights: [
            "Designed event identity systems and posters",
            "Shipped social media creatives for campus-wide events",
            "Collaborated with event teams on visual direction"
          ]
        },
        {
          icon: "HeartHandshake",
          title: "NSO Volunteer (70+ hours)",
          description: "Volunteered at the National Sports Organization wing of the university.",
          tag: "Service",
          year: "2022 \u2014 2024",
          story: "Logged 70+ volunteer hours with the National Sports Organization wing \u2014 supporting tournaments, training camps, and community sports outreach run by the university.",
          highlights: [
            "70+ verified volunteer hours with the NSO wing",
            "Supported tournament logistics and on-ground operations",
            "Contributed to community sports outreach"
          ]
        }
      ]
    },
    {
      degree: "B.S, Data Science and Applications",
      specialization: "Data Science",
      institution: "Indian Institute of Technology (IIT), Madras",
      duration: "2024 - Present",
      grade: "CGPA: 7.87/10"
    }
  ],
  languages: ["English", "Tamil", "Hindi", "Sanskrit"]
};
var skills = {
  languages: ["Python", "C/C++", "Java", "JavaScript", "HTML/CSS", "LaTeX", "MySQL"],
  frameworks: ["LangChain", "LangGraph", "Flask", "React.js", "PyTorch", "TensorFlow"],
  tools: ["Git", "GitHub", "Postman", "Arduino IDE", "VS Code", "Jupyter", "Azure", "Linux"],
  domains: ["GenAI", "RAG Pipelines", "LLMs", "IoT", "Machine Learning", "Data Science"]
};
var certifications = [
  { name: "Postman API Fundamentals Student Expert", issuer: "Postman" },
  { name: "Microsoft Azure Cloud Services", issuer: "Coursera" },
  { name: "Enterprise Design Thinking Practitioner", issuer: "IBM" },
  { name: "Programming in Modern C++", issuer: "IIT Kharagpur - NPTEL" },
  { name: "Data Science and Analytics", issuer: "HP Foundation" },
  { name: "Cyber Security Trends & Emerging Applications", issuer: "CyberTEA - IIIT Sri City" },
  { name: "Introduction to LLMs", issuer: "IIT Delhi - NPTEL" }
];
var experience = [
  {
    role: "Firmware Engineer",
    team: "Embedded Software (ESW) Group",
    company: "Logitech",
    type: "Full-time",
    duration: "Feb 2026 - Present",
    location: "Chennai, Tamil Nadu \xB7 On-site",
    highlights: [
      "Promoted from intern to full-time after delivering the CI failure-analysis automation work end-to-end during the NPI cycle.",
      "Owning firmware test automation across NPI builds \u2014 designing reliable, reproducible test harnesses for embedded peripherals and shipping them into the production CI pipeline.",
      "Hardening the LLM-assisted log triage system for daily engineering use: scaling across large log volumes, taming token and rate limits, and tightening clustering so failures land on the right owner the first time."
    ],
    technologies: ["Embedded C/C++", "Firmware Test Automation", "GitHub Actions", "CI/CD", "Python", "LLMs"],
    roles: [
      {
        role: "Firmware Engineer",
        team: "Embedded Software (ESW) Group",
        type: "Full-time",
        duration: "Jul 2026 - Present",
        highlights: [
          "Owning firmware test automation across NPI builds \u2014 designing reliable, reproducible test harnesses for embedded peripherals.",
          "Productionising the CI failure-analysis pipeline built during the internship and extending it to new product lines."
        ],
        technologies: ["Embedded C/C++", "Firmware Test Automation", "GitHub Actions", "Python", "LLMs"]
      },
      {
        role: "DevOps and Test Automation Intern",
        type: "Internship",
        duration: "Feb 2026 - Jun 2026 \xB7 5 mos",
        highlights: [
          "Automated CI failure analysis during NPI runs \u2014 built a log processing pipeline inside GitHub Actions that reads test logs, extracts failure details, summarises them using LLMs, and clusters similar issues to cut duplicate debugging.",
          "Made the system stable under real workloads \u2014 large log sizes, token limits, API rate limits, parallel execution and clustering accuracy \u2014 reducing manual log reading time and structuring failure triage for engineering teams."
        ],
        technologies: ["GitHub Actions", "CI/CD", "LLMs", "Python", "Log Processing", "DevOps"]
      }
    ]
  },
  {
    role: "GenAI Intern",
    company: "Prodapt Solutions Pvt. Ltd.",
    type: "Internship",
    duration: "May 2025 - Jul 2025",
    location: "Chennai, Tamil Nadu",
    highlights: [
      "Designed and deployed enterprise-grade Proof-of-Concepts (PoC) solutions at the intersection of Generative AI and Machine Learning, showcasing intelligent AI agents, autonomous task handlers, and workflow optimizers for clients across telecom, media, and allied industries.",
      "Engineered multi-agent systems using LangGraph, LangChain, and Gemini APIs, incorporating RAG pipelines, LLM fine-tuning, and vector databases to demonstrate technical feasibility and drive client-specific solutioning for global sales enablement."
    ],
    technologies: ["LangChain", "LangGraph", "Gemini APIs", "RAG", "LLMs", "Vector Databases"]
  },
  {
    role: "Research Intern",
    company: "Indian Institute of Information Technology, Design and Manufacturing (IIIT-D&M), Kancheepuram",
    type: "Internship",
    duration: "Dec 2024 - Jan 2025",
    location: "Kancheepuram, Tamil Nadu",
    highlights: [
      "Extensively worked on a real-time project using Reinforcement Learning (RL) based-routing on IoT Networks, Localization and Trilateration using Raspberry Pi, ESP-32 & UWB (Ultra Wideband) Sensor.",
      "Implemented routing solutions and prototypes using Decawave DW1000 Library in the Hybrid Intelligence Lab, Department of Computer Science.",
      "Collaborated on dataset collection, experiments, and documentation for research publications."
    ],
    technologies: ["Raspberry Pi", "ESP-32", "UWB Sensors", "Reinforcement Learning", "IoT Networks", "Python"]
  },
  {
    role: "Machine Learning Intern",
    company: "Suvidha Foundation",
    type: "Internship",
    duration: "Jan 2024 - Feb 2024",
    location: "Nagpur, Maharashtra (Remote)",
    highlights: [
      "Conducted Exploratory Data Analysis (EDA) and preprocessed 10,000+ raw data points, optimizing training efficiency by 30% through advanced pipelines in Python and TensorFlow, improving model accuracy by 37%.",
      "Boosted model accuracy by 20% via feature selection and dimensionality reduction, leveraging Scikit-learn and NumPy.",
      "Built and validated ML pipelines and pre-processing scripts; supported model evaluation and wrote reports summarizing findings and recommendations."
    ],
    technologies: ["Python", "TensorFlow", "Scikit-learn", "NumPy", "Pandas", "Data Analysis"]
  }
];
var projects = [
  {
    title: "IntelliRisk",
    subtitle: "AI Powered Risk Evaluation Engine for Engineering Product Compliance",
    category: "GenAI",
    description: "Built a full-stack AI-powered PoC for engineering compliance using LLMs (Google Gemini), dual FAISS VectorStores, and RAG pipelines to semantically compare original and alternate product components.",
    highlights: [
      "Automated parsing of engineering documents (.docx, .csv) and enabled intelligent section-level retrieval and report generation with compliance scores and explainable risk ratings.",
      "Deployed a Streamlit-based interface for dynamic input and report generation, integrating Markdown/Word outputs."
    ],
    technologies: ["Python", "LangChain", "Streamlit", "FAISS", "Gemini APIs", "Pandas"],
    date: "July 2025",
    github: "https://github.com/achyuth-2308/IntelliRisk-AI-Powered-Risk-Evaluation-Engine",
    featured: true
  },
  {
    title: "SmartSeal",
    subtitle: "IoT-based Smart Anti-Tampering Solution for Secure Deliveries",
    category: "IoT",
    description: "Developed an IoT-based smart anti-tampering solution for secure deliveries using embedded sensors and real-time monitoring.",
    highlights: [
      "Real-time tampering detection and alerts",
      "Secure delivery verification system"
    ],
    technologies: ["Arduino", "ESP32", "IoT Sensors", "MQTT", "React"],
    date: "2024",
    github: "https://github.com/achyuth-2308/SmartSeal-IoT-based-Smart-Anti-Tampering-Solution-for-Secure-Deliveries",
    featured: true
  },
  {
    title: "GestureGenius",
    subtitle: "Virtual Cursor Commander",
    category: "Computer Vision",
    description: "Hand gesture-controlled virtual mouse using computer vision and machine learning for touchless interaction.",
    highlights: [
      "Real-time hand tracking and gesture recognition",
      "Mouse control without physical contact"
    ],
    technologies: ["Python", "OpenCV", "MediaPipe", "NumPy"],
    date: "2024",
    github: "https://github.com/achyuth-2308/GestureGenius-Virtual-Cursor-Commander",
    featured: true
  },
  {
    title: "EquiBot",
    subtitle: "Self-Balancing Bot",
    category: "IoT",
    description: "A self-balancing robot using PID control algorithms and sensor fusion for stable autonomous movement.",
    highlights: [
      "PID control implementation for balance",
      "Real-time sensor data processing"
    ],
    technologies: ["Arduino", "MPU6050", "DC Motors", "PID Control"],
    date: "2024",
    github: "https://github.com/achyuth-2308/EquiBot-Self-Balancing-Bot",
    featured: true
  },
  {
    title: "SafeStep",
    subtitle: "Smart IoT Safety Net for Elderly",
    category: "IoT",
    description: "An IoT-based safety monitoring system designed to protect elderly individuals with fall detection and emergency alerts.",
    highlights: [
      "Fall detection using accelerometer data",
      "Emergency alert system for caregivers"
    ],
    technologies: ["ESP32", "Accelerometer", "Firebase", "React Native"],
    date: "2024",
    github: "https://github.com/achyuth-2308/SafeStep-Smart-IoT-Safety-Net",
    featured: true
  },
  {
    title: "EcoSphereX",
    subtitle: "IoT-Based Integrated Monitoring System for Environmental Health",
    category: "IoT",
    description: "Monitoring system providing reliable data on Noise, Air, and pH levels using IoT Sensors to enhance environmental quality and assess habitability.",
    highlights: [
      "STIRS Grant Award recipient - Rs.10,000/-",
      "Presented at IIT Madras AIRSS 2025"
    ],
    technologies: ["Arduino IDE", "NodeMCU ESP8266", "DHT-11", "Soil Sensor", "MQTT Protocol"],
    date: "Aug 2023 - Feb 2025",
    github: "https://github.com/achyuth-2308/EcoSphereX-IoT-Based-Integrated-Monitoring-System-for-Environmental-Health",
    featured: true
  }
];
var researchPhilosophy = `I've always been drawn to problems that sit right at the edge of technology and humanity. What excites me most is the idea that intelligence doesn't need to come at the cost of privacy. That's what pushed me into privacy-preserving AI, especially federated learning for IoT and wearable systems, where data stays where it belongs \u2014 with the person, at the edge, not in a distant server.

My work in healthcare AI comes from a simple belief: predictions are powerful only when trust is preserved. Building efficient on-device models for sensitive medical and sensor data fascinates me because it forces creativity \u2014 making models smaller, smarter, faster, and more respectful of the people they serve.

Lately, my curiosity has shifted toward the invisible side of AI \u2014 implicit and intersectional bias in LLMs. BADx was born from frustration with static bias tests that don't reflect how models behave when they "wear" personas. Studying how bias changes under context, and how we can explain it clearly, keeps me hooked.

To me, research isn't about publishing papers \u2014 it's about proving that we can build systems that are intelligent, cautious, and fair at the same time. If a model I build or audit makes even one person trust AI a little more, or protects one piece of sensitive data, I consider that real progress.`;
var researchProfiles = {
  googleScholar: "https://scholar.google.com/citations?user=zMSeQwQAAAAJ&hl=en",
  researchGate: "https://www.researchgate.net/profile/Achyuth-Mukund/research",
  orcid: "https://orcid.org/my-orcid?orcid=0009-0002-5798-0858"
};
var publications = [
  {
    number: "01",
    title: "The Synergy of Federated Learning and IoT: Pioneering Privacy and Efficiency in Decentralised Systems",
    authors: "Achyuth Mukund, T. Aditya Varun, Dr. K. B. Sundharakumar",
    year: "2025",
    venue: "ICCIDS 2025",
    publisher: "Springer",
    doi: "10.1007/978-3-031-98360-3_6",
    linkedinPost: "https://www.linkedin.com/feed/update/urn:li:activity:7296823234719621120/",
    mediumPost: "https://medium.com/@achyuth_2308/from-conference-halls-to-real-world-impact-a-journey-into-federated-learning-and-iot-6d46e20fdcdc",
    status: "published",
    images: ["publications/iccids-presentation.png", "publications/iccids-certificate.png"],
    abstract: "This paper explores the integration of Federated Learning with Internet of Things ecosystems, demonstrating how decentralized machine learning can preserve data privacy while maintaining model accuracy. We present a comprehensive framework for implementing privacy-preserving AI in distributed IoT networks."
  },
  {
    number: "02",
    title: "Wearable Technology and Sensor Data in Assistive Systems: Enhancing Rehabilitation Through Predictive Analytics",
    authors: "Achyuth Mukund",
    year: "2025",
    venue: "Predictive Algorithms for Rehabilitation and Assistive Systems",
    publisher: "IGI Global Scientific Publishing",
    doi: "10.4018/979-8-3373-0194-5.ch010",
    linkedinPost: "https://www.linkedin.com/feed/update/urn:li:activity:7339959639381327873/",
    status: "published",
    images: ["publications/igi-global-wearable.png"],
    abstract: "This chapter examines how wearable sensors and predictive analytics can transform rehabilitation practices. We discuss methodologies for collecting, processing, and analyzing sensor data to provide personalized rehabilitation recommendations and real-time progress monitoring."
  },
  {
    number: "03",
    title: "Enhancing Security in Federated Learning for Healthcare Data Sharing",
    authors: "Achyuth Mukund",
    year: "2025",
    venue: "Building Secure Ecosystems: Advances in Privacy-Preserving Machine Learning",
    publisher: "Apple Academic Press (CRC Press, Taylor & Francis Group), Burlington, Canada",
    doi: null,
    linkedinPost: null,
    status: "in-press",
    abstract: "This book chapter addresses critical security challenges in federated learning implementations for healthcare environments. We propose novel security mechanisms to protect sensitive medical data during collaborative model training across distributed healthcare institutions."
  },
  {
    number: "04",
    title: "Invisible Influences: Investigating Implicit Intersectional Biases through Persona Engineering in Large Language Models",
    authors: "Nandini Arimanda, Achyuth Mukund, Dr. Sakthi Balan Muthiah, Dr. Rajesh Sharma",
    year: "2026",
    venue: "18th ACM Web Science Conference (WebSci '26)",
    publisher: "ACM",
    doi: "10.1145/3795766.3799772",
    linkedinPost: "https://www.linkedin.com/posts/achyuth-mukund_websci2026-acmwebsci-research-ugcPost-7466625351813640193-hrlK/",
    newsArticle: "https://www.snuchennai.edu.in/from-snu-chennai-to-germany-cse-students-present-ai-research-at-acm-websci-2026/",
    status: "published",
    featured: true,
    conferenceDate: "May 26\u201329, 2026",
    conferenceLocation: "Technische Universit\xE4t Braunschweig, Germany",
    sessionInfo: "Session 5 \u2014 Framing, Fairness, and Privacy \xB7 Chaired by Dr. Eelco Herder",
    images: [
      "publications/websci/websci-presenting-1.jpg",
      "publications/websci/websci-presenting-2.jpg",
      "publications/websci/websci-presenting-3.jpg"
    ],
    abstract: "Presented in person at the 18th ACM Web Science Conference at Technische Universit\xE4t Braunschweig, Germany \u2014 celebrating 20 Years of Web Science. The paper introduces BADx (Bias Amplification Differential and Explainability Score), a novel framework that quantifies how bias in large language models shifts when the model is prompted to adopt different social personas and intersectional identities. Moving beyond static, single-axis benchmarks, BADx delivers a dynamic, context-sensitive lens on implicit bias across five state-of-the-art LLMs, paired with an explainability layer that surfaces why a model drifts. The work, co-authored with Nandini Arimanda, Dr. Sakthi Balan Muthiah (SNU Chennai) and Dr. Rajesh Sharma (Plaksha University), was accepted into the official WebSci '26 proceedings and presented in Session 5 \u2014 Framing, Fairness, and Privacy."
  }
];
var timeline = [
  { year: "2026", event: "Presented at ACM WebSci 2026, Technische Universit\xE4t Braunschweig, Germany" },
  { year: "2026", event: "DevOps & Test Automation Intern at Logitech" },
  { year: "2025", event: "GenAI Intern at Prodapt" },
  { year: "2025", event: "Published in IGI Global" },
  { year: "2025", event: "AIRSS 2025 Presentation at IIT Madras" },
  { year: "2024-25", event: "Research Intern at IIIT D&M Kancheepuram" },
  { year: "2024", event: "Started B.S at IIT Madras" },
  { year: "2024", event: "ML Intern at Suvidha Foundation" },
  { year: "2024", event: "STIRS Grant Award" },
  { year: "2023", event: "Started EcoSphereX Project" },
  { year: "2022", event: "Joined Shiv Nadar University" }
];
var achievements = [
  {
    title: "ACM WebSci 2026 \u2014 International Presenter",
    year: "2026",
    description: "Travelled to Germany to present 'Invisible Influences' at the 18th ACM Web Science Conference, Technische Universit\xE4t Braunschweig \u2014 in Session 5: Framing, Fairness, and Privacy.",
    organization: "ACM \xB7 Technische Universit\xE4t Braunschweig, Germany"
  },
  {
    title: "STIRS Grant Award",
    year: "2024",
    description: "Recognized for excellence in research and received a grant of Rs.10,000/- for the EcoSphereX project",
    organization: "Shiv Nadar University Chennai"
  },
  {
    title: "IIT Madras AIRSS 2025",
    year: "2025",
    description: "Shortlisted and selected to present EcoSphereX project at All India Research Scholar Summit",
    organization: "IIT Madras"
  },
  {
    title: "World Record Ensemble",
    year: "2023",
    description: "Participated as a keyboardist in a world record music ensemble",
    organization: "Music Community"
  }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Achyuth Mukund's profile: name, location, current focus, bio, education (degrees, institutions, CGPA, coursework), languages spoken, and public links (GitHub, LinkedIn, ORCID, Google Scholar, ResearchGate).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: personalInfo.name,
      location: personalInfo.location,
      tagline: personalInfo.tagline,
      summary: personalInfo.description,
      contact: { email: personalInfo.email, phone: personalInfo.phone },
      links: personalInfo.social,
      bio: about.bio,
      education: about.education.map((entry) => ({
        degree: entry.degree,
        specialization: entry.specialization ?? null,
        institution: entry.institution,
        duration: entry.duration,
        grade: entry.grade,
        coursework: entry.coursework ?? []
      })),
      languages: about.languages
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List work experience",
  description: "List Achyuth Mukund's professional work experience, including company, role, team, dates, location, responsibilities and technologies, plus the internal role progression within each company.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List Achyuth Mukund's engineering projects with descriptions, highlights, technologies, dates and GitHub links. Optionally filter to featured projects or search by keyword.",
  inputSchema: {
    featuredOnly: z.boolean().nullable().describe("When true, return only featured projects."),
    query: z.string().nullable().describe("Optional keyword to match against project title, description or technologies.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ featuredOnly, query }) => {
    let results = projects;
    if (featuredOnly) {
      results = results.filter((project) => project.featured === true);
    }
    if (query) {
      const needle = query.toLowerCase();
      results = results.filter(
        (project) => JSON.stringify(project).toLowerCase().includes(needle)
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, projects: results }
    };
  }
});

// src/lib/mcp/tools/list-publications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_publications_default = defineTool4({
  name: "list_publications",
  title: "List research publications",
  description: "List Achyuth Mukund's research publications and book chapters with authors, venue, publisher, year, DOI, publication status and abstracts, along with his research philosophy and scholarly profile links (Google Scholar, ResearchGate, ORCID).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      publications: publications.map((entry) => {
        const { images: _images, ...rest } = entry;
        return rest;
      }),
      researchPhilosophy,
      researchProfiles
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_skills_default = defineTool5({
  name: "list_skills",
  title: "List skills and certifications",
  description: "List Achyuth Mukund's technical skills grouped by languages, frameworks, tools and domains, together with his professional certifications and their issuing organisations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { skills, certifications };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-awards.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/data/awards.ts
var awards = [
  {
    id: "guinness-keyboard",
    title: "Guinness World Record \u2014 Largest Keyboard Ensemble",
    issuer: "Guinness World Records",
    year: "2014",
    category: "World Record",
    featured: true,
    description: "Star Performer in Samarpan \u2014 Music for World Peace, an ensemble of 229 keyboardists conducted by Isaimaamani M. S. Martin and organised by Mellifluous Melodies on Keyboard at the Chennai Trade Centre on 16 January 2014. The ensemble was officially recognised by Guinness World Records as the largest keyboard ensemble.",
    highlights: [
      "229-member keyboard ensemble \xB7 Chennai Trade Centre, Nandambakkam",
      "Conducted by Isaimaamani M. S. Martin",
      "Officially adjudicated and certified by Guinness World Records"
    ]
  },
  {
    id: "stirs-grant",
    title: "STIRS Research Grant \u2014 EcoSphereX",
    issuer: "Shiv Nadar University Chennai",
    year: "2023 \u2014 24",
    category: "Research",
    description: "Awarded a competitive \u20B910,000 research grant under the STIRS programme to build EcoSphereX, an IoT-based integrated environmental health monitoring system.",
    highlights: [
      "Project ID: STIR2023_IIMSEH",
      "Sensor stack: ESP8266, MQTT, multi-parameter air & water sensors",
      "Mentored end-to-end from proposal to working prototype"
    ],
    link: {
      label: "EcoSphereX on GitHub",
      url: "https://github.com/achyuth-2308/EcoSphereX-IoT-Based-Integrated-Monitoring-System-for-Environmental-Health"
    }
  },
  {
    id: "airss-iitm",
    title: "Presenter \u2014 All India Research Scholars' Summit",
    issuer: "IIT Madras",
    year: "2025",
    category: "Research",
    description: "Selected to present EcoSphereX (OP106) at AIRSS 2025 \u2014 IIT Madras' flagship research summit, alongside scholars from across the country."
  },
  {
    id: "central-perk",
    title: "Founder \u2014 Central Perk Caf\xE9",
    issuer: "Shiv Nadar University Chennai",
    year: "2023 \u2014 Present",
    category: "Leadership",
    description: "Kickstarted the university's first ever student-run entrepreneurial venture on campus \u2014 from concept and branding to operations."
  },
  {
    id: "mun-vp",
    title: "Vice President \u2014 SNUC MUN Society",
    issuer: "Shiv Nadar University Chennai",
    year: "2024 \u2014 25",
    category: "Leadership",
    description: "Led conference operations, delegate experience and inter-college outreach as VP of the MUN Society."
  },
  {
    id: "cultural-coord",
    title: "Overall Cultural & Club Coordinator",
    issuer: "Shiv Nadar University Chennai",
    year: "2024 \u2014 25",
    category: "Cultural",
    description: "Coordinated cultural programming and inter-club activities across the university's student body."
  },
  {
    id: "cricket",
    title: "University Cricket Team",
    issuer: "Shiv Nadar University Chennai",
    year: "2022 \u2014 Present",
    category: "Sports",
    description: "Selected to represent the university's prestigious cricket team in inter-collegiate fixtures."
  },
  {
    id: "ambassador",
    title: "Student Ambassador",
    issuer: "Shiv Nadar University Chennai",
    year: "2023 \u2014 Present",
    category: "Leadership",
    description: "Represented the university to prospective students, parents and visiting delegations."
  },
  {
    id: "nso",
    title: "70+ Volunteer Hours \u2014 NSO",
    issuer: "National Sports Organization, SNUC",
    year: "2022 \u2014 24",
    category: "Community",
    description: "Logged 70+ hours volunteering with the university's NSO wing across sports events and outreach."
  }
];

// src/lib/mcp/tools/list-awards.ts
var list_awards_default = defineTool6({
  name: "list_awards",
  title: "List awards and milestones",
  description: "List Achyuth Mukund's awards, honours and recognitions (including the Guinness World Record, NCC and research honours) alongside his career timeline and notable achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      awards,
      timeline,
      achievements
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "achyuth-mukund-portfolio",
  title: "Achyuth Mukund \u2014 Portfolio",
  version: "1.0.0",
  instructions: "Read-only access to Achyuth Mukund's professional portfolio. Use `get_profile` for biography, education and contact links; `list_experience` for work history; `list_projects` for engineering projects (filterable); `list_publications` for research papers, DOIs and abstracts; `list_skills` for the technical stack and certifications; and `list_awards` for honours, the career timeline and achievements. All data is public and static.",
  tools: [
    get_profile_default,
    list_experience_default,
    list_projects_default,
    list_publications_default,
    list_skills_default,
    list_awards_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
